### ISSUE TITLE
Delete "add_compile_definitions( DEBUG_OPT )" in pers2cyc_inf

### ISSUE THREAD

**Issue by taohou01** [Sayan-m90/Minimum-Persistent-Cycles#1]
The DEBUG_OPT will do some unnecessary check which may slow down the program

**Comment by Sayan-m90** [comment]
Wait this is not related to the code Tamal asked is it?
Or is this an email from GitHub about the update?

[image: The Ohio State University]
Sayan Mandal
Graduate Student
College of Engineering | Computer Science and Engineering Dept.
Dreese Lab, 2015 Neil Avenue, Columbus, OH 43210
(614) 292-2572 Office
sayan.mandal@gmail.com mandal.25@osu.edu

*Buckeyes consider the environment before printing.*

Personal Webpage <http://web.cse.ohio-state.edu/~mandal/> | G+
<https://www.google.com/+sayanmandalkgp> | Linked-In
<http://in.linkedin.com/pub/sayan-mandal/92/38a/523/.in> | Alternate-email
<mesayaan@gmail.com> | Facebook <https://www.facebook.com/sayaan.mandal> |
YouTube <https://www.youtube.com/+sayanmandalkgp>

**Comment by taohou01** [comment]
This is an issue I posted about my codes assigned to me which serves as a
reminder for me to correctify this ... This should not be relevant to you.

Sayan Mandal <notifications@github.com> 于2019年11月7日周四 上午10:56写道：

> Wait this is not related to the code Tamal asked is it?
> Or is this an email from GitHub about the update?
>
> [image: The Ohio State University]
> Sayan Mandal
> Graduate Student
> College of Engineering | Computer Science and Engineering Dept.
> Dreese Lab, 2015 Neil Avenue, Columbus, OH 43210
> (614) 292-2572 Office
> sayan.mandal@gmail.com mandal.25@osu.edu
>
> *Buckeyes consider the environment before printing.*
>
> Personal Webpage <http://web.cse.ohio-state.edu/~mandal/> | G+
> <https://www.google.com/+sayanmandalkgp> | Linked-In
> <http://in.linkedin.com/pub/sayan-mandal/92/38a/523/.in> | Alternate-email
> <mesayaan@gmail.com> | Facebook <https://www.facebook.com/sayaan.mandal> |
> YouTube <https://www.youtube.com/+sayanmandalkgp>
>
>
>
